### ISSUE TITLE
Development Snapshot is not found

### ISSUE THREAD

**Issue by Kcchouette** [fabienwang/omgcss#1]
Hey

Thanks for this awesome css framework.

I'm trying to use it for https://github.com/Kcchouette/XDCC-fetcher!

But the development snapshot is not found!

I can instead link to
```
<link href="https://fabienwang.github.io/omgcss/dist/css/omg.css" rel="stylesheet">
<script src="https://fabienwang.github.io/omgcss/dist/js/omg.js"></script>
```

**Comment by fabienwang** [comment]
Hello,
thanks.

There are no release at the moment so yeah you can just Download the full repository or do as you did :)
