### ISSUE TITLE
Changing mouse pointer for menubtn

### ISSUE THREAD

**Issue by Kcchouette** [fabienwang/omgcss#2]
I just add `.menubtn {
	cursor: pointer;
}` in my code to do that.

And it's better, isn't it?

**Comment by fabienwang** [comment]
This was added in OMGCSS v2 but I never released it.
The idea was to use Gulp, use different sources files like menu.css buttons.css etc. and compile it all to a single distribution file. Also I tried to remove the JS part but failed.

I'll see if I can push it into another branch.
Thanks.
